#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("mem_interfaces_request_address_address0", 1, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("mem_interfaces_request_address_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("mem_interfaces_request_address_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("mem_interfaces_request_data_address0", 1, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("mem_interfaces_request_data_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("mem_interfaces_request_data_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("mem_interfaces_request_op_V_address0", 1, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("mem_interfaces_request_op_V_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("mem_interfaces_request_op_V_q0", 2, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("mem_interfaces_result_address0", 1, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("mem_interfaces_result_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("mem_interfaces_result_we0", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("mem_interfaces_result_d0", 32, hls_out, 3, "ap_memory", "mem_din", 1),
	Port_Property("mem_interfaces_ack_V_address0", 1, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("mem_interfaces_ack_V_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("mem_interfaces_ack_V_we0", 1, hls_out, 4, "ap_memory", "mem_we", 1),
	Port_Property("mem_interfaces_ack_V_d0", 1, hls_out, 4, "ap_memory", "mem_din", 1),
	Port_Property("mem_interfaces_req_V_address0", 1, hls_out, 5, "ap_memory", "mem_address", 1),
	Port_Property("mem_interfaces_req_V_ce0", 1, hls_out, 5, "ap_memory", "mem_ce", 1),
	Port_Property("mem_interfaces_req_V_q0", 1, hls_in, 5, "ap_memory", "mem_dout", 1),
};
const char* HLS_Design_Meta::dut_name = "global_memory";
